name: tlfs
description: The Local First SDK.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  ffigen: ^4.1.0
  test: ^1.19.2

ffigen:
  output: 'lib/tlfs_capi.dart'
  headers:
    entry-points:
    - '../capi/tlfs.h'
    include-directives:
    - '../capi/tlfs.h'
  typedef-map:
      'uintptr_t': 'Uint64'
