[package]
name = "tlfs-cambria-example"
version = "0.1.0"
edition = "2018"
publish = false

[build-dependencies]
tlfs-cambria = { path = ".." }

[dependencies]
rkyv = "0.7.15"
tlfs-cambria = { path = ".." }
